# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - uses: szenius/set-timezone@v2.0
      with:
          timezoneLinux: "Australia/Melbourne"
          timezoneMacos: "Australia/Melbourne"
          timezoneWindows: "Australia/Melbourne"
    - run: swift test --enable-code-coverage
    - uses: drekka/swift-coverage-action@v1.1
      with:
        show-all-files: true
