# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: szenius/set-timezone@v1.2
      with:
          timezoneLinux: "Australia/Melbourne"
          timezoneMacos: "Australia/Melbourne"
          timezoneWindows: "Australia/Melbourne"
    - uses: BinaryBirds/swift-test-report@0.0.1
    #- name: Build
    #  run: swift build -v
    - name: Run tests
      run: |
        sudo xcode-select -s /Applications/Xcode_15.0.app
        swift test -v
